language: node_js
node_js:
  - "5.0"


addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.8
env:
  global:
    - region="us-east-1"
    - CXX=g++-4.8
    - secure: "M/HdyTiCRp5PBoTbpb8+lf18WivcstcpINnzsX6KvvGI5KHkJ982W3eZfpDJD9yl12SKBYbysoEy32+c+lEsN+wDzxebcqInNaLFHRaixQZklJzCbho8WDzA9rv6OXGGQ9gUaudWVEAW/zK2SBzo+Tr9JZ/oCB9QWBivSeVjkd/lIpecizhAGYc3KbVOuXX2CPgGbpC1LROEm85ikA+wQFqLhQJXE6uSwE5a6cXZRc1V4RmJUSgioD7AvJExzpz08Fzlg3cZdjf8aNs0iaTAoB/5P26jmJMIAHKERxkMARPw/fuZgP96MTxKrHFCD+lA/nfYJ/2mqgsu+6yG58EUpvfb8TQWeu3zXy12vzqwwi9EgUvzhJNNMzbGUVdkUzpD0taeDZ82fh8abW0xLN6ro5Tlw2xu0njGn/OhEgzrV7CFOEs7M+Dt+Qf6xggZ4c5GeiK75xNv8M/qszixE6mtMWL2i1NIXrvYAj7e7Tbs3Yo+1SOazhopDLZ89ZsdyNoiuhuEwgPaUv2/7PdcWwY7BNusTu69Zx4R8/UFN63hVPAVa8nRhj4sWT1m0jhvsnxOJY1l53w2FemGB0y/fBCQyoaiZAzOwDZUnvu2XqHjBTr7FQ0CJxGIhPH1FcBOzawWaafbJ/Q9IlcL4ABfUQ5ugadfOwt53JT0S8fmFx0U7AE="
    - secure: "f05wI1v+A5pa/ASKbWu3+4/GO64xlq8vPsyMhf9DpEhu6P6rT7M6hc/L6n+FTo+5v81diNy9x1cVdJhAQOvccBMWL/0RSm44/ieSD84+Bu/hWM4WunVwNelelPqUZld/PSS/XbPitGcBVqZcw3ieXiGTXKsncPuaGln6qjDQfPPFKSDlnVbfzkck0mp7iKdaHoMrvCup2S3PjHkKC6Qj7A0+JTx1gEut7KY/LQf1sXU1cXraM2Id38T3H83KxXVEtETyYbtTqV+flbLNr+HLr077kH/5jh0xCskKa2LzlXhi8u7ImBp61Z14y7IBwrQWFvZw/6awNO5kdgmkq1TqPZFigwD+VdMat64OgqQW7Evq0miOI6X6DtAlAoYOfElsRz44CuL1Kr7jleu+GhyS+SSVPrfYRSPG6S8jG60Ft0iVgE2DbbmOSTidLVYoXKLbOfttVffw3U67LPDtsLnaLvuVHwCWmdre4fzYQZnlViE4r8ptWSayCOdHH/mOgYSEt5MA1rKGgB9cz2AvwbnMYlHVFVbCMEFr4yUQUewDm57v6nmbwFMZ6pizE8Qp4v6sZnh2WHC91YOV/G1zCkV8OGBiXvSMI5yi9fxVUaxJAYzAKpMAaJV6Iv575i0Eru7466DL9qeRW67OfDlBrgppGjVkepcLMYmzO7K/idqyV7A="
before_install:
  - $CXX --version
  - case ${TRAVIS_NODE_VERSION} in 0.8*|0.10*) npm install -g npm@2 ;; esac
  - cd test
  - npm install
  - cd ../app
  - npm install -g npm
  - npm install
  - cd ../backend
install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - $CXX --version
  - npm install -g mocha casperjs phantomjs gulp
script:
  - npm install && npm test

after_success:
  - gulp lambda