name: test backend

on:
  push:
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string
      - cron:  '0 */6 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: 1.x
      - run: npm run test:backend
