name: test frontend

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - run: npm ci
      - run: __VERCEL_SKIP_DEV_CMD=true npm run vercel:dev &
      - run: npx wait-on http://localhost:3000
      - run: npm run test:e2e
