name: test e2e

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Use Deno
          uses: denolib/setup-deno@v2
          with:
            deno-version: 1.x
      - shell: bash
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          npm ci
          npm run vercel:dev &
          npm run test:e2e
