name: test end to end

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '15'
      - run: PUPPETEER_PRODUCT=firefox npm ci
      - name: Waiting for 200 from the Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@master
        id: waitFor200
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 60
      - run: PUPPETEER_EXECUTABLE_PATH="/usr/bin/google-chrome-stable" URL=${{steps.waitFor200.outputs.url}} npm run test:e2e
     

